### ISSUE TITLE
Wheel Ticks calculation error cause GPS jumps on mowgli hardware. 

### ISSUE THREAD

**Issue by kevinmce** [ClemensElflein/open_mower_ros#100]
Im looking to track the issue identified in this conversation: https://discord.com/channels/958476543846412329/1079054431758332027/1235330953065267281

Jump in wheel ticks identified by c.ez:
![image](https://github.com/ClemensElflein/open_mower_ros/assets/2911414/bc72e46e-5db6-4ec1-bac1-74b53778473f)
> yes, that definitively had an error in the sign, also the large jumps are not GPS, you can verify that the GPS plot is not jumping, but the position is. it's wheel ticks jumping!

Identified that its when wheel tick direction change is triggered that a wheel tick jump occurs. 
![image](https://github.com/ClemensElflein/open_mower_ros/assets/2911414/9dc97f86-5f90-4897-98b0-496908d576d5)

Recommendation from Nekraus :
Nekraus — 05/02/2024 8:51 PM
in robot localization in function onWheelTicks : 
`   
    if(abs(vx) > 0.6) {
        ROS_WARN_STREAM("got vx > 1.0 (" << vx << ") - dropping measurement");
        vx = 0.0;
        is_vx_valid = false;
        return;
    }`

**Comment by ClemensElflein** [comment]
This jump detection and fix belons in the Mowgli codebase

**Comment by kevinmce** [comment]
Sorry, i though the wheel ticks are calculated in the openmower OS? I suppose ill raise the ticket there.
