### ISSUE TITLE
Dev Container?

### ISSUE THREAD

**Issue by jeremysalwen** [ClemensElflein/open_mower_ros#109]
Does anyone have a dev container they use for development?  I tried repurposing the included dockerfile, but I found a ton of gotchas that have still prevented it from working for me.

**Comment by ClemensElflein** [comment]
I have pushed my setup, you can look at the `devenv` folder which contains a dockerized ros-noetic-desktop full install.

You should be able to:
```
git clone --recursive https://github.com/ClemensElflein/open_mower_ros
cd open_mower_ros/devenv
./start_devenv.sh
./attach.sh
```

and then inside the bash compile
```
cd /workspace && catkin_make
```

I don't use VS code, but writing a compatible devcontainer.json should be fairly straightforward from this.

I hope it helps.

**Comment by ClemensElflein** [comment]
Also GUI tools like RVIZ and plotjuggler should work out of the box with this.
