### ISSUE TITLE
Recovery behavior

### ISSUE THREAD

**Issue by jeremysalwen** [ClemensElflein/open_mower_ros#142]
I'm posting this here since I posted in the Discord chat but it wasn't noticed.

I want to make a PR to allow the mower to back up and try again when it gets stuck. 90% of the time my mower gets stuck (on my admittedly difficult yard), I can solve it through remote teleoperation by moving directly forward and/or backwards a bit and trying again.

However, I am not sure the best approach in the code to do this.  move_base does seem to have built in support for recovery behaviors: https://medium.com/@patiladitya1309/recovery-behaviours-used-in-navigation-stack-ros-5df991f408c7  But I know that OpenMower does things a bit custom.  Would it be better to create a separate behavior for it?  or just a helper function that we can call when appropriate to try recovering?

(also note this output in the logs complaining about no recovery behaviors):

```
[ INFO] [1723432482.850780446]: The plugin with the type "global_planner/GlobalPlanner" has been loaded successfully under the name "GlobalPlanner".
[ INFO] [1723432482.911912005]: FTCLocalPlannerROS: Version 2 Init.
[ INFO] [1723432482.912024003]: The plugin with the type "ftc_local_planner/FTCPlanner" has been loaded successfully under the name "FTCPlanner".
[ INFO] [1723432482.965198797]: FTCLocalPlannerROS: Version 2 Init.
[ INFO] [1723432482.965410542]: The plugin with the type "ftc_local_planner/FTCPlanner" has been loaded successfully under the name "DockingFTCPlanner".
[ WARN] [1723432482.966065026]: No recovery_behaviors plugins configured! - Use the param "recovery_behaviors", which must be a list of tuples with a name and a type.
```

**Comment by ClemensElflein** [comment]
Sorry for missing this on Discord initially, I think this is answered by now
