### ISSUE TITLE
triggering dynamic obstacles in simulator

### ISSUE THREAD

**Issue by greymfm** [ClemensElflein/open_mower_ros#24]
Hello,
I managed to compile the code on an Ubuntu 18.04 system (i7). The simulator works. 

Question: Is dynamic obstacle avoidance already implemented? How could we trigger dynamic obstacle in the simulator? 
If it is not yet implemented, how about switching to 'teb_local_planner' for the obstacle avoidance? Once detected an obstacle (bumper trigger etc.), one could add a circle in the cost map in front of the robot and then use the 'teb_local_planner' to navigate around it...

**Comment by ClemensElflein** [comment]
No, dynamic obstacle avoidance is not implemented yet. Triggering could be done by publishing a point in RVIZ and adding a circle for that into the costmap for example.


Yes I had planned to use teb_local_planner (also for navigating between mowing areas and to the dock and so on), it worked well in sim but I didn't get it tuned fast enough for the pi (it was like 2 Hz update rate for the control output).


If you want to work on this, I'd suggest joining the Discord and asking in the #open-mower-software channel. The user PaddyCube mentioned he also wants to work on it and wants to use TEB planner. No need to do the work twice.
