### ISSUE TITLE
topic for publishing action

### ISSUE THREAD

**Issue by dudz40** [ClemensElflein/open_mower_ros#30]
Hi Clemens, writing an integration into a home automation product for openmower. So far so good. Seem to have an issue getting the actions executed. I am publishing to the **action** topic, it looks like the allowed actions are in topic **actions**. But so far the mower does not react when i publish a message. What are the messages you are expecting on what topic? Thank you so much.

**Comment by jerome83136** [comment]
Hi
I'm about to start building an Open Mower
I have the robot; now I'm reading all docs carefully while waiting for the other parts to be delivered
I'm pretty intersted in the possibilities for smart home integration. How can I find any documentation about this ? (Available API ? Http endpoint ? Mqtt topics ? Local scripts to interface with for controlling the mower?)

I can see we are taking about mqtt topics here; could someone share some docs describing Open Mower mqtt implementation maybe? 😊

Thank you very much for your help
Best regards

**Comment by jerome83136** [comment]
Hello everyone,
Someone to share something on this maybe?
Thank you for your help
Best regards

**Comment by tommarek** [comment]
Hey! Join the discord - this has been spoken about a few times already. You can run a MQTT bridge (drafted by docgalaxyblock here: https://github.com/ClemensElflein/OpenMowerOS/commit/4932feca3699aa41906614674ae52c3daebf7178 ) on your openmower and then publish actions via that.

**Comment by jerome83136** [comment]
Hi,
Thank you for the tip
See you all soon on discord then 😊
Best regards
