### ISSUE TITLE
Leaving Emergency while mowing set the state to Docking

### ISSUE THREAD

**Issue by alexvaut** [ClemensElflein/open_mower_ros#52]
- In mowing state
- Lift or tilt the mower
=> the mower goes to emergency mode
- Before the mower goes to Idle after 1-2 minutes, press unlock for 2 seconds
=> the mower goes to docking state
Since the user decided to leave the emergency mode, the mower should just continue to conitnue as it was (mowing state). If the user wants the mower to go back to the docking station then he should request expliticly to move to the docking state (by pressing the home button for instance).

**Comment by 2m** [comment]
Yup, makes total sense! Wondering if all of the current state (current mowing area and progress of the area) is not lost, when mower enters emergency state.

**Comment by ClemensElflein** [comment]
True, thank you for reporting

**Comment by olliewalsh** [comment]
IIRC problem is that emergency aborts the current behavior - https://github.com/ClemensElflein/open_mower_ros/blob/55a3fde766d9d6906e915121c75ffac8c6628d1d/src/mower_logic/src/mower_logic/mower_logic.cpp#L387

@2m No state lost etc... it just goes into the next state i.e Docking

**Comment by 2m** [comment]
I have also noticed this problem when mowing some bumpy grass for the first time yesterday. I have created a PR (https://github.com/ClemensElflein/open_mower_ros/pull/65) that removes the mentioned `abortExecution()` call. Let me know if that makes sence. I will try to test it out the mower with this change.
