### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by alexandrzlobin** [ClemensElflein/open_mower_ros#69]
`[ 76%] Built target xbot_positioning_generate_messages
[ 76%] Building CXX object lib/xbot_positioning/CMakeFiles/xbot_positioning.dir/src/xbot_positioning_core.cpp.o
[ 76%] Building CXX object lib/xbot_positioning/CMakeFiles/xbot_positioning.dir/src/xbot_positioning.cpp.o
/home/zlo/lawn_mower/src/lib/xbot_positioning/src/xbot_positioning.cpp:12:10: fatal error: xbot_msgs/AbsolutePose.h: No such file or directory
 #include "xbot_msgs/AbsolutePose.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
lib/xbot_positioning/CMakeFiles/xbot_positioning.dir/build.make:89: recipe for target 'lib/xbot_positioning/CMakeFiles/xbot_positioning.dir/src/xbot_positioning.cpp.o' failed
make[2]: *** [lib/xbot_positioning/CMakeFiles/xbot_positioning.dir/src/xbot_positioning.cpp.o] Error 1
CMakeFiles/Makefile2:15499: recipe for target 'lib/xbot_positioning/CMakeFiles/xbot_positioning.dir/all' failed
make[1]: *** [lib/xbot_positioning/CMakeFiles/xbot_positioning.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
`
Why this file missing? 
I use ros melodic

**Comment by ClemensElflein** [comment]
It should be generated during compilation. Either you are missing a git submodule, or it's an issue with Melodic. OpenMower is ROS noetic.
