### ISSUE TITLE
Path crosses not allowed areas

### ISSUE THREAD

**Issue by karlranseierausrom** [ClemensElflein/open_mower_ros#76]
![Screenshot_20240203-104750](https://github.com/ClemensElflein/open_mower_ros/assets/43208283/59d841ca-6eb3-48a8-ba37-fd2c66115cb9)
![Screenshot_20240202-182417](https://github.com/ClemensElflein/open_mower_ros/assets/43208283/0092034e-9367-4b66-8dd1-2bdb76de2b5f)

In both cases the mower tries to drive through an area where he is not allowed to. In the beginning I thought it is a lack of gps signal, but then for s hort moment I saw, that there was an orange, in my understanding planned, path through this area.

It might be related to https://github.com/ClemensElflein/open_mower_ros/issues/63 . I installed the patch, but it did not help.

**Comment by karlranseierausrom** [comment]
I did a mistake when patching. I will try it tomorrow to do it correctly.

**Comment by karlranseierausrom** [comment]
https://github.com/ClemensElflein/slic3r_coverage_planner/pull/3 solved the problem

**Comment by karlranseierausrom** [comment]
Today my mower tried to go swimming. It will be solved with the changes in #63 . Please change the coverage planner for the next version.

**Comment by 11phc** [comment]
yes same happening to me on Edge version date 19/4/2024.  Seems to be related to having a tiny triangle area to mow. Near an obstacle.  Great that we have a fix lined up.  🙏

**Comment by ClemensElflein** [comment]
@11phc could you please share your map?

**Comment by 11phc** [comment]
![30652B25-D5BA-4F50-874E-FB38D93661C3_1_101_o](https://github.com/ClemensElflein/open_mower_ros/assets/10351369/42a6c411-aa8f-4916-9e23-40c11dfae9db)
![878674F5-9991-4188-A62C-D879EBB680A8_1_105_c](https://github.com/ClemensElflein/open_mower_ros/assets/10351369/809fc0c5-9d41-4759-8bdc-be0ffcd2876e)
 This is a photo of the screen (not great) and I have overwritten with new maps now with an obstacle blocking the relevant point, but it's that tiny bit on the right hand side between the rectangles and the outer boundary.  Would you like better pictures / map / gpx? I can do it

**Comment by ClemensElflein** [comment]
I'll close this one, it's the same as #63

**Comment by 11phc** [comment]
on your xtech email Clemans, thanks 🙏
